### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by BUI-studies** [ohiienko-r/js-08-dom-hw#1]
Воно звісно працює. 

Але сказали шо це читабельно буде важко. 

Для початку позапиховуй у змінні усе шо ти зі сторінки забираєш, бо в іфай воно виглядає ну максимально не читабельно.
Потім виділи окремо фнукцію яка б отримувала текстконтент елемнету, і повертала б колір в залежності від того якіки там відсотків.

**Comment by ohiienko-r** [comment]
0)Записав увесь контент, який я збираю зі сторінки у змінні.

1)Поки що не зовсім розумію де мені дописати ту функцію яка б збирала текст контект і робила основну роботу, бо в мене все запихано в один forEach. **Треба коментар-допомога.**

![image](https://user-images.githubusercontent.com/109099364/235465470-a6322805-1c36-45c7-a2f2-59bfb7019b24.png)

**Comment by BUI-studies** [comment]
по-перше це уже в рази приємніше виглядає)

по-друге - `lineToUpdate.style/color = getColor(actualValue, goalValue)` десь отак це має виглядати

**Comment by ohiienko-r** [comment]
UPD 

![image](https://user-images.githubusercontent.com/109099364/235642495-7501f275-4169-4fe1-8c39-a9eaec47bda0.png)

**Comment by ohiienko-r** [comment]
UPD

![image](https://user-images.githubusercontent.com/109099364/235650026-efa7940c-3aac-45e5-ae0d-4129eb2d6887.png)
